-- velafi-lark-inbox-pack: velafi-owned Lark inbox-notification queries.
-- Re-homed 2026-07-15 (v0.4.x): upstream deleted the monolithic lark.sql /
-- lark.sql.go when it moved Lark into the channel layer; these velafi queries
-- (used by inbox_notifier.go) live here and are regenerated by sqlc.

-- name: ListActiveLarkUserBindingsByMember :many
-- Outbound notification path: find the recipient's bound Lark accounts in
-- this workspace, with the active bot installation needed for credentials.
-- Re-homed onto channel_* (MUL-3515): reads channel_user_binding +
-- channel_installation (channel_type='feishu') instead of the retired lark_*
-- tables, so it sees installations/bindings created AFTER the Lark->channel
-- cutover (upstream now writes only channel_*), not just backfilled rows. The
-- feishu credentials (app_id, app_secret_encrypted, tenant_key, bot_open_id,
-- bot_union_id, region) live in ci.config JSONB and the recipient open_id is
-- cub.channel_user_id; the Go caller decodes config via installationFromRow.
-- channel_* has no FK (MUL-3515 §4), so the workspace match is enforced here.
SELECT sqlc.embed(cub), sqlc.embed(ci)
FROM channel_user_binding cub
JOIN channel_installation ci ON ci.id = cub.installation_id
WHERE cub.workspace_id = $1
  AND cub.multica_user_id = $2
  AND cub.channel_type = 'feishu'
  AND ci.channel_type = 'feishu'
  AND ci.workspace_id = cub.workspace_id
  AND ci.status = 'active'
ORDER BY cub.bound_at DESC;

-- name: ClaimLarkInboxNotificationDelivery :one
-- Claims one outbound Lark inbox notification delivery. This is intentionally
-- keyed by the durable inbox_item row plus the concrete bot installation and
-- recipient open_id so repeated inbox:new events, duplicate bus subscribers,
-- or multi-replica handling cannot send duplicate DMs.
WITH ins AS (
    INSERT INTO lark_inbox_notification_delivery (
        inbox_item_id,
        installation_id,
        lark_open_id
    ) VALUES ($1, $2, $3)
    ON CONFLICT DO NOTHING
    RETURNING true AS claimed
)
SELECT COALESCE((SELECT claimed FROM ins), false)::boolean AS claimed;

-- name: DeleteLarkInboxNotificationDelivery :exec
DELETE FROM lark_inbox_notification_delivery
WHERE inbox_item_id = $1
  AND installation_id = $2
  AND lark_open_id = $3;

-- name: ClaimLarkInboxCommentDelivery :one
-- velafi-lark-inbox-pack: claims ONE Lark card per comment + installation +
-- recipient, collapsing the `mentioned` + `new_comment` inbox-item pair multica
-- emits for a single @mention comment into a single delivery. Race-safe via PK.
WITH ins AS (
    INSERT INTO lark_inbox_comment_delivery (
        comment_id,
        installation_id,
        lark_open_id
    ) VALUES ($1, $2, $3)
    ON CONFLICT DO NOTHING
    RETURNING true AS claimed
)
SELECT COALESCE((SELECT claimed FROM ins), false)::boolean AS claimed;

-- name: DeleteLarkInboxCommentDelivery :exec
-- velafi-lark-inbox-pack: releases a comment-delivery claim when the send
-- fails, so a later retry can re-claim.
DELETE FROM lark_inbox_comment_delivery
WHERE comment_id = $1
  AND installation_id = $2
  AND lark_open_id = $3;

